// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eaxejnjbbrlusmhvikzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVheGVqbmpiYnJsdXNtaHZpa3pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTEyNTcsImV4cCI6MjA3MzE4NzI1N30.sjrML8LUcD3Xw9yPfJ3oz7_bxx95NanYaI2c4IcEcXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});